import { parseLabValues } from './labParser';

// Fixed ISO timestamps — avoids SSR hydration mismatch (module-level Date.now() differs per runtime)
export const MOCK_DOCUMENTS = [
  {
    id: 'mock-001',
    name: 'lab_results_march_2026.pdf',
    fileType: 'application/pdf',
    size: 124800,
    uploadedAt: '2026-03-14T09:30:00.000Z',
    status: 'ready',
    isMock: true,
    textContent: `CLINICAL LABORATORY REPORT\n\nPatient Name: Sarah Mitchell\nPatient ID: PT-2026-04521\nDate of Birth: 14/08/1982\nAttending Physician: Dr. James Harrington\nDate Collected: 14 March 2026\n\nCOMPLETE BLOOD COUNT (CBC)\nHemoglobin: 12.8 g/dL (Normal: 12.0-16.0)\nWhite Blood Cell Count: 7.2 x 10^3/uL (Normal: 4.5-11.0)\nPlatelet Count: 245 x 10^3/uL (Normal: 150-400)\nHematocrit: 38.4% (Normal: 36-46)\n\nMETABOLIC PANEL\nGlucose: 98 mg/dL (Normal: 70-100)\nCreatinine: 0.9 mg/dL (Normal: 0.6-1.2)\nSodium: 140 mEq/L\n\nLIPID PANEL\nTotal Cholesterol: 195 mg/dL\nLDL: 118 mg/dL\nHDL: 52 mg/dL\nTriglycerides: 130 mg/dL\n\nCONCLUSION: Results within normal reference range. Follow-up recommended in 6 months.`,
    analysis: {
      classification: { type: 'Lab Report', confidence: 0.94 },
      entities: {
        persons: ['Sarah Mitchell', 'Dr. James Harrington'],
        dates: ['14/08/1982', '14 March 2026'],
        organizations: ['Clinical Laboratory'],
        medications: [],
      },
      metrics: {
        'Patient ID': 'PT-2026-04521',
        'Date of Birth': '14/08/1982',
        'Attending Physician': 'Dr. James Harrington',
        'Primary Diagnosis': 'Results within normal reference range',
      },
      summary: 'Complete blood count and metabolic panel results for patient Sarah Mitchell show all values within normal reference ranges. Lipid panel shows total cholesterol of 195 mg/dL with LDL 118 mg/dL. Follow-up recommended in 6 months.',
      patientName: 'Sarah Mitchell',
      labValues: parseLabValues(`COMPLETE BLOOD COUNT (CBC)\nHemoglobin: 12.8 g/dL (Normal: 12.0-16.0)\nWhite Blood Cell Count: 7.2 x 10^3/uL (Normal: 4.5-11.0)\nPlatelet Count: 245 x 10^3/uL (Normal: 150-400)\nHematocrit: 38.4% (Normal: 36-46)\n\nMETABOLIC PANEL\nGlucose: 98 mg/dL (Normal: 70-100)\nCreatinine: 0.9 mg/dL (Normal: 0.6-1.2)\nSodium: 140 mEq/L\n\nLIPID PANEL\nTotal Cholesterol: 195 mg/dL\nLDL: 118 mg/dL\nHDL: 52 mg/dL\nTriglycerides: 130 mg/dL`),
    },
  },
  {
    id: 'mock-002',
    name: 'discharge_summary_jones.pdf',
    fileType: 'application/pdf',
    size: 98304,
    uploadedAt: '2026-02-28T11:00:00.000Z',
    status: 'ready',
    isMock: true,
    textContent: `DISCHARGE SUMMARY\n\nPatient Name: Robert Jones\nPatient ID: PT-2026-03847\nDate of Birth: 22/03/1955\nAdmission Date: 24 February 2026\nDischarge Date: 28 February 2026\nAttending Physician: Dr. Priya Sharma\n\nCHIEF COMPLAINT: Acute chest pain with shortness of breath.\n\nHOSPITAL COURSE: Mr. Jones was admitted via emergency department with acute onset chest pain. ECG showed ST changes. Troponin levels were mildly elevated. Patient was managed with aspirin 300mg and anticoagulation therapy. Echocardiogram performed on day 2 showed preserved ejection fraction. Patient stabilised over 48 hours.\n\nDISCHARGE MEDICATIONS: Aspirin 75mg daily, Atorvastatin 40mg nightly, Metoprolol 25mg twice daily.\n\nDISCHARGE INSTRUCTIONS: Rest for 2 weeks. Avoid strenuous activity. Follow-up with cardiology in 4 weeks.\n\nNext Appointment: 28 March 2026 at 10:00am, Cardiology Clinic.`,
    analysis: {
      classification: { type: 'Discharge Summary', confidence: 0.96 },
      entities: {
        persons: ['Robert Jones', 'Dr. Priya Sharma'],
        dates: ['22/03/1955', '24 February 2026', '28 February 2026', '28 March 2026'],
        organizations: ['Cardiology Clinic'],
        medications: ['Aspirin', 'Atorvastatin', 'Metoprolol'],
      },
      metrics: {
        'Patient ID': 'PT-2026-03847',
        'Date of Birth': '22/03/1955',
        'Attending Physician': 'Dr. Priya Sharma',
        'Primary Diagnosis': 'Acute chest pain with shortness of breath',
        'Next Appointment': '28 March 2026 at 10:00am, Cardiology Clinic',
      },
      summary: 'Robert Jones was admitted with acute chest pain and shortness of breath. ECG showed ST changes with mildly elevated troponin. Managed with aspirin and anticoagulation; discharged on aspirin, atorvastatin, and metoprolol with cardiology follow-up in 4 weeks.',
      patientName: 'Robert Jones',
    },
  },
  {
    id: 'mock-003',
    name: 'prescription_amoxicillin.pdf',
    fileType: 'application/pdf',
    size: 43008,
    uploadedAt: '2026-03-02T08:15:00.000Z',
    status: 'ready',
    isMock: true,
    textContent: `PRESCRIPTION\n\nPatient Name: Emily Carter\nPatient ID: PT-2026-05102\nDate of Birth: 30/11/1990\nDate: 02 March 2026\nPrescribing Physician: Dr. Alan Brooks\nLicence No: GMC-7845123\n\nRx:\n1. Amoxicillin 500mg capsule — Take 1 capsule three times daily for 7 days\n2. Ibuprofen 400mg tablet — Take 1 tablet twice daily with food as needed for pain\n\nDiagnosis: Acute tonsillitis\n\nAllergies: None known\nRepeat: No\n\nPharmacy: St. Mary's Medical Centre Pharmacy\nSigned: Dr. Alan Brooks\nDate: 02 March 2026`,
    analysis: {
      classification: { type: 'Prescription', confidence: 0.97 },
      entities: {
        persons: ['Emily Carter', 'Dr. Alan Brooks'],
        dates: ['30/11/1990', '02 March 2026'],
        organizations: ["St. Mary's Medical Centre Pharmacy"],
        medications: ['Amoxicillin', 'Ibuprofen'],
      },
      metrics: {
        'Patient ID': 'PT-2026-05102',
        'Date of Birth': '30/11/1990',
        'Attending Physician': 'Dr. Alan Brooks',
        'Primary Diagnosis': 'Acute tonsillitis',
      },
      summary: 'Prescription for Emily Carter for acute tonsillitis. Prescribed amoxicillin 500mg three times daily for 7 days alongside ibuprofen 400mg twice daily as needed. No known allergies; non-repeat prescription.',
      patientName: 'Emily Carter',
    },
  },
  {
    id: 'mock-004',
    name: 'mri_report_brain.pdf',
    fileType: 'application/pdf',
    size: 215040,
    uploadedAt: '2026-01-21T15:45:00.000Z',
    status: 'ready',
    isMock: true,
    textContent: `MRI BRAIN REPORT\n\nPatient Name: David Nguyen\nPatient ID: PT-2026-02981\nDate of Birth: 07/04/1978\nReferring Physician: Dr. Susan Lee\nDate of Scan: 21 January 2026\nReporting Radiologist: Dr. Kemal Ozturk\n\nEXAMINATION: MRI Brain without contrast\n\nINDICATION: Persistent headaches and visual disturbances.\n\nFINDINGS:\nBrain volume appears normal for age. No focal parenchymal signal abnormality. No restricted diffusion to suggest acute ischaemia. Ventricles are normal in size. No midline shift. No extra-axial collections. Orbits appear normal. Visualised paranasal sinuses are clear.\n\nIMPRESSION: Normal MRI brain. No acute intracranial abnormality identified. Clinical correlation recommended.\n\nNext Appointment: Follow-up with neurology on 14 February 2026.`,
    analysis: {
      classification: { type: 'Imaging Report', confidence: 0.95 },
      entities: {
        persons: ['David Nguyen', 'Dr. Susan Lee', 'Dr. Kemal Ozturk'],
        dates: ['07/04/1978', '21 January 2026', '14 February 2026'],
        organizations: [],
        medications: [],
      },
      metrics: {
        'Patient ID': 'PT-2026-02981',
        'Date of Birth': '07/04/1978',
        'Attending Physician': 'Dr. Kemal Ozturk',
        'Primary Diagnosis': 'Normal MRI brain. No acute intracranial abnormality identified',
        'Next Appointment': 'Follow-up with neurology on 14 February 2026',
      },
      summary: 'MRI brain without contrast for David Nguyen indicated for persistent headaches and visual disturbances. All findings within normal limits — no focal abnormality, ischaemia, or midline shift. Clinical correlation recommended with neurology follow-up scheduled.',
      patientName: 'David Nguyen',
    },
  },
  {
    id: 'mock-005',
    name: 'referral_cardiology_kowalski.pdf',
    fileType: 'application/pdf',
    size: 61440,
    uploadedAt: '2026-04-10T16:00:00.000Z',
    status: 'ready',
    isMock: true,
    textContent: `REFERRAL LETTER\n\nDate: 10 April 2026\nFrom: Dr. Helen Walsh, GP\nTo: Cardiology Department, Royal General Hospital\n\nDear Dr. Specialist,\n\nRe: Ms. Anna Kowalski, DOB: 15/06/1965, Patient ID: PT-2026-06234\n\nI would be grateful if you could kindly review Ms. Kowalski, who has been experiencing exertional chest tightness and palpitations over the past 3 months. Her resting ECG shows occasional ectopics but is otherwise unremarkable. BP is 145/92 mmHg on two readings.\n\nBackground: Type 2 diabetes (on Metformin 1g twice daily), hypertension (Lisinopril 10mg daily). Non-smoker. Family history of ischaemic heart disease.\n\nI would appreciate your assessment and any further investigations you deem appropriate.\n\nKind regards,\nDr. Helen Walsh\nGP, Parkside Medical Practice`,
    analysis: {
      classification: { type: 'Referral Letter', confidence: 0.93 },
      entities: {
        persons: ['Anna Kowalski', 'Dr. Helen Walsh'],
        dates: ['15/06/1965', '10 April 2026'],
        organizations: ['Royal General Hospital', 'Parkside Medical Practice'],
        medications: ['Metformin', 'Lisinopril'],
      },
      metrics: {
        'Patient ID': 'PT-2026-06234',
        'Date of Birth': '15/06/1965',
        'Attending Physician': 'Dr. Helen Walsh',
        'Primary Diagnosis': 'Exertional chest tightness and palpitations',
      },
      summary: 'Referral from Dr. Helen Walsh to cardiology for Anna Kowalski presenting with exertional chest tightness and palpitations over 3 months. Background of Type 2 diabetes and hypertension with a family history of ischaemic heart disease. Resting ECG shows occasional ectopics.',
      patientName: 'Anna Kowalski',
    },
  },
];
